consul:
    hostname: consul
    container_name: consul
    image: qnib/consul
    environment:
    - DC_NAME=dc1
    - RUN_SERVER=true
    - BOOTSTRAP_CONSUL=true
    ports:
    - "8500:8500"
    dns: 127.0.0.1

samza:
    hostname: samza
    container_name: samza
    dns: 127.0.0.1
    image: qnib/samza
    environment:
    - DC_NAME=dc1
    links:
    - consul:consul
    ports:
    - 8042:8042
    - 8088:8088
    - 50070:50070
    privileged: true

